#!/bin/bash 


cor1="\033[1;31m"
cor2="\033[1;32m"
cor3="\033[1;33m"
cor4="\033[1;34m"
cor5="\033[1;35m"
cor6="\033[1;36m"
cor7="\033[1;37m"
fc="\033[m"
op1="$cor4[$cor1 1 $cor4] $fc"
op2="$cor4[$cor1 2 $cor4] $fc"
op3="$cor4[$cor1 3 $cor4] $fc"
op4="$cor4[$cor1 4 $cor4] $fc"
op5="$cor4[$cor1 5 $cor4] $fc"
op6="$cor4[$cor1 6 $cor4] $fc"
op7="$cor4[$cor1 7 $cor4] $fc"
op8="$cor4[$cor1 8 $cor4] $fc"
op9="$cor4[$cor1 9 $cor4] $fc"

space="┃                                               ┃"

model1="\e[1;36m
╭> Personalizavel \e[1;31m>>\e[1;32m>\e[1;36m \w \e[m\e[1;36m
╰$"

model2="
┏━━(Personalizavel)━[\w]
┗━$ "

model3="
┏━[Personalizavel]-[\w]
┗━■ $"
model4="
┏❲Personalizavel❳━❲📂\w❳
┗ᗒ "

style1s="x>>"
style1d="<<x"
style2s="-->"
style2d="<--"
style3s="<<"
style3d=">>"
style4s="=>"
style4d="<="
style5s="[<"
style5d=">]"
style6s="●❯"
style6d="❮●"
bar1t="╔══════════════════════════════════════════╗"
bar1m="╠══════════════════════════════════════════╣"
bar1b="╚══════════════════════════════════════════╝"
bar1s="║                                          ║"



clear
echo -e "$cor3
$bar1t
║       $cor6 assistente termux $fc      $cor3          ║
$bar1m
$bar1s
║   $op1 $style6s Start systemas $style6d $cor3           ║
$bar1s
║   $op2 $fc$style6s Criar projetos Web $style6d$fc$cor3        ║
$bar1s
║   $op3 $fc$style6s Custom termux $style6d$fc$cor3             ║
$bar1s
$bar1b
";
read menu

if [ $menu == 1 ]
then
	clear
	echo -e "$cor3
$bar1t
║         $cor2      Start systemas $fc$cor3            ║
$bar1m
$bar1s
║ $op1 $fc$style6s Iniciar apache2🚀 $style6d$fc$cor3           ║
$bar1s
║ $op2 $fc$style6s Parar apach2   🛑 $style6d$fc$cor3           ║
$bar1s
║ $op3 $fc$style6s Iniciar Myadmin🚀 $style6d$fc$cor3           ║
$bar1s
║ $op4 $fc$style6s Parar Myadmin  🛑 $style6d$fc$cor3           ║ 
$bar1s
║ $op5 $fc$style6s Iniciar MYSQL  🚀 $style6d$fc$cor3           ║ 
$bar1s
║ $op6 $fc$style6s Parar   MYSQL  🛑 $style6d$fc$cor3           ║
$bar1s
$bar1b
"
read op
if [ $op == 1 ]
then
	apachectl start
elif [ $op == 2 ] 
then
	apachectl stop
elif [ $op == 3 ]
then
	cd /data/data/com.termux/files/usr/share/phpmyadmin
	php -S localhost:5050
elif [ $op == 4 ]
then
	kill php
elif [ $op == 5 ]
then
	mysqld
elif [ $op == 6 ]
then
	/data/data/com.termux/files/usr/etc/init.d/mysql stop
fi

elif [ $menu == 2 ]
then
	clear
	echo -e "
$bar1t
║$cor6  Criação de diretórios rapido e simples$fc$cor3  ║
$bar1m
║         $cor1 Todos os Projetos vai ≺╗        $cor3║
║$cor1  localizar na pasta My_project ≺╝        $cor3║
$bar1m
$bar1s
║   $op1 $fc$style6s   Projeto📚 em PHP $style6d$fc$cor3        ║
$bar1m
$bar1s
║   $op2 $fc$style6s   Projeto📚 HTML5  $style6d$fc$cor3        ║
$bar1m
$bar1s
║   $op3 $fc$style6s   Projeto📚 VueJS  $style6d$fc$cor3        ║
$bar1m
$bar1s
║   $op4 $fc$style6s Projeto📚 VueJS+NuxsJS  $style6d$fc$cor3   ║
$bar1b
"
read projeto

 if [ $projeto == 1 ]
 then
	 clear
	 echo -e "
	\033[1;42;33m  Arvore de diretórios    \033[m
	\033[1;47;31m   📁 My_project≺╮        
	 \033[1;47;31m  ╭─────────────╯        
	 \033[1;47;31m  ╰≻📂 Nome_do_projeto≺╮ 
	 \033[1;47;31m                       │ 
	 \033[1;47;31m        📁 style≺──────┤ 
	 \033[1;47;31m        📁 js≺─────────┤ 
	 \033[1;47;31m        📁 imgs≺───────┤ 
	 \033[1;47;31m        📋 index.php≺──╯ \033[m
	 "
	 echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
	 echo -e "$cor2 Nome do projeto"
	 read project
	 mkdir /storage/emulated/0/My_project/ $project > /dev/null 2>&1

	 mkdir Conexao > /dev/null 2>&1
	 mkdir Style > /dev/null 2>&1
	 mkdir Js > /dev/null 2>&1
	 mkdir Imgs > /dev/null 2>&1

	 mv Conexao /storage/emulated/0/My_project/$project/ > /dev/null 2>&1
	 mv Style /storage/emulated/0/My_project/$project/ > /dev/null 2>&1
	 mv Js /storage/emulated/0/My_project/$project/ > /dev/null 2>&1
	 mv Imgs /storage/emulated/0/My_project/$project/ > /dev/null 2>&1

	 touch /storage/emulated/0/My_project/$project/index.php

	 rm /data/data/com.termux/files/home/$project > /dev/null 2>&1

	 




 fi
elif [ $menu == 3 ]
then

sleep 5
clear
echo -e "$cor3

                ┏━━━━━━━━━━━━━━━━━━━━━┓
    ┏━━━━━━━━━━━┫     TMX-CUSTOM      ┣━━━━━━━━━━━━━┓
    ┃           ┗>By MTplys WebSystm <┛             ┃
    ┃                                               ┃
    ┃                                               ┃
    ┃              ╭───╮                            ┃
    ┃            ╭─┤ 𝟏 ├≻ Modelos Pronto            ┃
    ┃            │ ╰───╯                            ┃
    ┃            │                                  ┃
    ┃            │  ╭───╮                           ┃
    ┃   opções   │╭─┤ 𝟐 ├≻ Modelos com Edição       ┃
    ┃            ├╯ ╰───╯                           ┃
    ┃            │                                  ┃
    ┃            │   ╭───╮                          ┃
    ┃            │╭──┤ 𝟑 ├≻ Importar Modelo         ┃
    ┃ disponíveis├╯  ╰───╯                          ┃
    ┠────────────╯                                  ┃
    ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛"
    read style
    
fi
